services:
  web-users:
    build:
      context: ./components/users
      dockerfile: Dockerfile
    command: gunicorn composites.user_api:app --bind 0.0.0.0:8001
    env_file:
      - envs/.env.users
    restart: unless-stopped
    depends_on:
      - db_postgres
      - rabbitmq

  web-books:
    build:
      context: ./components/books
      dockerfile: Dockerfile
    command: gunicorn composites.book_api:app --bind 0.0.0.0:8002
    env_file:
      - envs/.env.books
    restart: unless-stopped
    depends_on:
      - db_postgres
      - rabbitmq

  book_consumer:
    build:
      context: ./components/books
      dockerfile: Dockerfile
    command: python3 -m composites.consumer
    env_file:
      - envs/.env.books.cons
    restart: unless-stopped
    depends_on:
      - db_postgres
      - rabbitmq

  user_consumer:
    build:
      context: ./components/users
      dockerfile: Dockerfile
    command: python3 -m composites.consumer
    env_file:
      - envs/.env.users.cons
    restart: unless-stopped
    depends_on:
      - db_postgres
      - rabbitmq

  db_postgres:
    build: ./components/postgres
    env_file:
      - envs/.env.db
    ports:
      - 5432:5432
    restart: unless-stopped
    depends_on:
      - rabbitmq

  nginx:
    build: ./components/gateway
    ports:
      - 1337:80
    restart: unless-stopped
    depends_on:
      - web-users
      - rabbitmq
      - db_postgres

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - envs/.env.rabbit

